{
	<|
		"Title"->"Eonian-イオニアン",
		"Description"->"",
		"Authors"->{"GalAster"},
		"Created"->DateObject[{2016,5,10}],
		"Music"->"Eonian-イオニアン",
		"MusicBy"->Missing,
		"Subtitle"-><|
			"Main"->"Eonian-イオニアン.ass",
			"Timeline"->Missing,
			"Fantasy"->"Eonian-イオニアン.fx.ass",
			"Description"->"",
			"Authors"->{"GalAster"}
		|>,
		"Video"-><|
			"URL"->"",
			"Description"->"",
			"Authors"-><|""|>
		|>
	|>
};